# Generated by Django 5.2 on 2025-04-09 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(choices=[('BG', 'Belgrade'), ('KG', 'Kragujevac'), ('E', 'Eastern Division')], max_length=2)),
                ('location_number', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('internal_number', models.CharField(max_length=100, unique=True)),
                ('inventory_number', models.CharField(max_length=100, unique=True)),
                ('account_number', models.CharField(max_length=100, unique=True)),
                ('machine_type', models.CharField(choices=[('TV', 'Transport Vehicle'), ('PV', 'Passenger Vehicle'), ('CV', 'Construction Vehicle'), ('OT', 'Other')], default='OT', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('under_maintenance', 'Under Maintenance')], default='active', max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machines.location')),
            ],
        ),
        migrations.CreateModel(
            name='ExpertReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('report_number', models.CharField(max_length=100, unique=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expert_reports', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_date', models.DateField()),
                ('number_of_installments', models.PositiveIntegerField()),
                ('annual_depreciation_rate', models.DecimalField(decimal_places=2, help_text='Percentage per year', max_digits=5)),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='value_info', to='machines.machine')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='machines.machine')),
            ],
        ),
    ]
